//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trench.User.Domain.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DomainValidationResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DomainValidationResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Trench.User.Domain.Resources.DomainValidationResource", typeof(DomainValidationResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string AlreadyUsernameExists {
            get {
                return ResourceManager.GetString("AlreadyUsernameExists", resourceCulture);
            }
        }
        
        public static string AlreadyEmailExists {
            get {
                return ResourceManager.GetString("AlreadyEmailExists", resourceCulture);
            }
        }
        
        public static string ErrorCreatingAccount {
            get {
                return ResourceManager.GetString("ErrorCreatingAccount", resourceCulture);
            }
        }
        
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        public static string AlreadyFollowerExists {
            get {
                return ResourceManager.GetString("AlreadyFollowerExists", resourceCulture);
            }
        }
        
        public static string FollowYourself {
            get {
                return ResourceManager.GetString("FollowYourself", resourceCulture);
            }
        }
        
        public static string FollowersNotFound {
            get {
                return ResourceManager.GetString("FollowersNotFound", resourceCulture);
            }
        }
    }
}
