services:
  trench-rabbitmq:
    image: rabbitmq:4.1.1-management
    container_name: trench-rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - trench-network